[github_app]
pr_commands = [
    "/review",
    "/describe"
]

[pr_reviewer]
persistent_comment = true
final_update_message = true
extra_instructions = """
Focus on the following aspects when reviewing Devin-generated code:
- Code quality and best practices
- TypeScript type safety
- React component patterns and hooks usage
- Integration with existing codebase patterns
- Performance considerations
- Security implications
"""
require_tests_review = true
require_security_review = true
require_estimate_effort_to_review = true
enable_review_labels_effort = true
enable_review_labels_security = true
num_max_findings = 5

[pr_description]
use_description_markers = true
include_generated_by_header = true
publish_description_as_comment = false
add_original_user_description = true
keep_original_user_title = true
