packages:
  - "frontend/apps/*"
  - "frontend/packages/*"
  - "frontend/packages/__mocks__/*"
  - "frontend/internal-packages/*"
minimumReleaseAge: 2880 # 2 days
minimumReleaseAgeExclude:
  # Renovate security update: valibot@1.2.0
  - valibot@1.2.0
