packages:
  - "frontend/apps/*"
  - "frontend/packages/*"
  - "frontend/packages/__mocks__/*"
  - "frontend/internal-packages/*"
minimumReleaseAge: 20160 # 14 days
minimumReleaseAgeExclude:
  - "@sentry/*"
