packages:
  - "frontend/apps/*"
  - "frontend/packages/*"
  - "frontend/packages/__mocks__/*"
  - "frontend/internal-packages/*"
minimumReleaseAge: 2880 # 2 days
minimumReleaseAgeExclude:
  # Renovate security update: @modelcontextprotocol/sdk@1.26.0
  - "@modelcontextprotocol/sdk@1.26.0"
  # Renovate security update: @langchain/community@1.1.14
  - "@langchain/community@1.1.14"
