name: pnpm-setup

inputs:
  working-directory:
    required: false
    type: string
    default: '.'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        package_json_file: ${{ inputs.working-directory }}/package.json
    - name: Setup node env
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: ${{ inputs.working-directory }}/.node-version
        cache: pnpm
        cache-dependency-path: ${{ inputs.working-directory }}/pnpm-lock.yaml
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts
      working-directory: ${{ inputs.working-directory }}
