import { prisma } from '@liam-hq/db'
import type { ReviewResponse } from '../types'

type GitHubClient = {
  createComment: (params: {
    owner: string
    repo: string
    issue_number: number
    body: string
  }) => Promise<{ data: { id: number; html_url: string } }>
}

type GitHubClientFactory = {
  createGitHubClientForInstallation: (installationId: number) => Promise<GitHubClient>
}

export const postComment = (githubClientFactory: GitHubClientFactory) => async (
  payload: ReviewResponse
): Promise<{
  success: boolean
  commentId?: number
  commentUrl?: string
  error?: { message: string; type: string }
}> => {
  try {
    // Get repository and PR data
    const pullRequest = await prisma.pullRequest.findUnique({
      where: {
        id: payload.pullRequestId,
      },
      include: {
        repository: true,
      },
    })

    if (!pullRequest) {
      throw new Error(`Pull request with ID ${payload.pullRequestId} not found`)
    }

    const octokit = await githubClientFactory.createGitHubClientForInstallation(
      Number(pullRequest.repository.installationId)
    )

    // Format the comment
    const formattedComment = `
# Database Schema Review

${payload.reviewComment}

---
*This review was automatically generated by Liam.*
    `.trim()

    // Post comment to GitHub
    const response = await octokit.createComment({
      owner: pullRequest.repository.owner,
      repo: pullRequest.repository.name,
      issue_number: Number(pullRequest.pullNumber),
      body: formattedComment,
    })

    // Update review record with comment ID and URL
    await prisma.review.updateMany({
      where: {
        pullRequestId: payload.pullRequestId,
      },
      data: {
        commentId: response.data.id,
        commentUrl: response.data.html_url,
      },
    })

    return {
      success: true,
      commentId: response.data.id,
      commentUrl: response.data.html_url,
    }
  } catch (error) {
    console.error('Error posting comment:', error)

    if (error instanceof Error) {
      return {
        success: false,
        error: {
          message: error.message,
          type: error.constructor.name,
        },
      }
    }

    return {
      success: false,
      error: {
        message: 'An unexpected error occurred',
        type: 'UnknownError',
      },
    }
  }
} 