export * from './getTableColumnElementId'
export * from './getTableColumnLinkHref'
export * from './getTableColumnLinkHref'
export * from './getTableIndexElementId'
export * from './getTableIndexLinkHref'
export * from './getTableLinkHref'
