name: Add assignee to PR

on:
  pull_request:
    types: [opened]

jobs:
  add-assignee-to-pr:
    permissions:
      pull-requests: write
    uses: route06/actions/.github/workflows/add_assignee_to_pr.yml@cf674a8d68a24bd75ac63171dc8e976e53024bbf # v2.7.5
