name: Database CI

on:
  pull_request:
    paths:
      - ".github/workflows/database-ci.yml"
      - "frontend/internal-packages/db/**"
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pg_tap_tests:
    name: PGTap Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: supabase/setup-cli@b60b5899c73b63a2d2d651b1e90db8d4c9392f51 # v1.6.0
        with:
          version: latest
      - name: Supabase Start
        run: supabase start
      - name: Setup supabase testing
        run: |
          psql -v ON_ERROR_STOP=1 -U postgres -d postgres -h localhost -p 54322 -f frontend/internal-packages/db/supabase/setup-testing.sql
        env:
          PGPASSWORD: postgres
      - name: Run Tests
        run: supabase test db
