on:
  discussion_comment:
    types: [created]

jobs:
  discussion_commented:
    if: github.event.discussion && github.event.comment
    permissions:
      contents: read
    uses: route06/actions/.github/workflows/gh_discussion_comment_to_slack.yml@cf674a8d68a24bd75ac63171dc8e976e53024bbf # v2.7.5
    secrets:
      slack-webhook-url: ${{ secrets.SLACK_GHD_WEBHOOK_URL }}
