name: E2E Tests

on:
  workflow_call:
    inputs:
      environment_val:
        required: true
        type: string
      target_url:
        required: true
        type: string
      sha:
        required: true
        type: string

concurrency:
  group: e2e-tests-${{ inputs.environment_val }}-${{ inputs.sha }}
  cancel-in-progress: false

jobs:
  _e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        browser: [chromium, 'Mobile Safari']
      fail-fast: false
    permissions:
      contents: read
      statuses: write
    defaults:
      run:
        working-directory: 'frontend/internal-packages/e2e'
    env:
      CI: true
      URL: ${{ inputs.target_url }}
      ENVIRONMENT: ${{ inputs.environment_val }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}
          persist-credentials: false

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml', '**/playwright.config.ts') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install Playwright browsers
        if: ${{ steps.playwright-cache.outputs.cache-hit != 'true' }}
        run: pnpm exec playwright install --with-deps

      - name: Install system dependencies for WebKit
        if: ${{ steps.playwright-cache.outputs.cache-hit == 'true' }}
        run: pnpm exec playwright install-deps webkit

      - name: Run E2E tests
        run: pnpm exec playwright test --project="${{ matrix.browser }}"
        env:
          URL: ${{ inputs.target_url }}

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.browser }}-${{ github.run_id }}-${{ github.job }}
          path: frontend/internal-packages/e2e/test-results/
          retention-days: 30

      - name: Post E2E status manually
        if: always()
        run: |
          STATE="${{ job.status }}"
          CONTEXT="E2E Tests / e2e-tests (${{ matrix.browser }})"
          gh api repos/${{ github.repository }}/statuses/${{ inputs.sha }} \
            --method POST \
            --field state="${STATE}" \
            --field context="${CONTEXT}" \
            --field description="E2E test result for ${{ matrix.browser }}: (${STATE})" \
            --field target_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
