name: E2E Tests

on:
  deployment_status:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        browser: [chromium, 'Mobile Safari']
      fail-fast: false

    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout repo for local action resolution
        uses: actions/checkout@v4

      - name: liam-app-e2e_tests
        if: github.event.deployment_status.state == 'success' &&
          contains(github.event.deployment.environment, 'Production') &&
          contains(github.event.deployment.environment, 'liam-app') &&
          contains(github.event.deployment_status.target_url, 'liam-app-git-main')
        uses: ./.github/actions/reusable-e2e
        with:
          browser: ${{ matrix.browser }}
          deployment-target: liam-app
          environment: ${{ github.event.deployment.environment }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.deployment.sha }}
          test-project: liam-app
          url: ${{ github.event.deployment_status.target_url }}

      - name: liam-erd-sample-e2e_tests
        if: github.event.deployment_status.state == 'success' &&
          contains(github.event.deployment_status.target_url, 'liam-erd-sample')
        uses: ./.github/actions/reusable-e2e
        with:
          browser: ${{ matrix.browser }}
          deployment-target: liam-erd-sample
          environment: ${{ github.event.deployment.environment }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.deployment.sha }}
          test-project: liam-erd-sample
          url: ${{ github.event.deployment_status.target_url }}
