name: E2E Tests

on:
  deployment_status:

jobs:
  liam-app-e2e_tests:
    if: github.event.deployment_status.state == 'success' &&
      contains(github.event.deployment.environment, 'Production') &&
      contains(github.event.deployment.environment, 'liam-app') &&
      contains(github.event.deployment_status.target_url, 'liam-app-git-main')
    uses: ./.github/workflows/reusable_e2e.yml
    with:
      working-directory: frontend/internal-packages/e2e
      test-project: liam-app
      environment: ${{ github.event.deployment.environment }}
      url: ${{ github.event.deployment_status.target_url }}
      ref: ${{ github.event.deployment.sha }}
      deployment-target: liam-app

  liam-erd-sample-e2e_tests:
    if: github.event.deployment_status.state == 'success' &&
      contains(github.event.deployment_status.target_url, 'liam-erd-sample')
    uses: ./.github/workflows/reusable_e2e.yml
    with:
      working-directory: frontend/internal-packages/e2e
      test-project: liam-erd-sample
      environment: ${{ github.event.deployment.environment }}
      url: ${{ github.event.deployment_status.target_url }}
      ref: ${{ github.event.deployment.sha }}
      deployment-target: liam-erd-sample
