name: E2E Tests

on:
  deployment_status:

concurrency:
  group: e2e-tests
  cancel-in-progress: false

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        browser: [chromium, 'Mobile Safari']
      fail-fast: false

    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout repo for local action resolution
        uses: actions/checkout@v4

      - name: liam-app-e2e_tests
        id: check
        shell: ruby {0}
        working-directory: ${{ github.workspace }}
        run: |
          event_name      = "${{ github.event_name }}"
          event_state     = "${{ github.event.deployment_status.state }}"
          environment_val = "${{ github.event.deployment.environment }}"
          target_url      = "${{ github.event.deployment_status.target_url }}"

          result =
            if event_name == "deployment_status" && event_state == "success"
              # Production deployment
              if environment_val.include?("Production") && target_url.include?("liam-app-git-main")
                "should_run=true"
              # Preview deployment
              elsif environment_val.include?("Preview") && !target_url.include?("liam-erd-sample") && !target_url.include?("liam-docs") && !target_url.include?("liam-storybook")
                "should_run=true"
              else
                "should_run=false"
              end
            else
              "should_run=false"
            end

          # Same as 'echo "should_run=xxxx" >> $GITHUB_OUTPUT'
          output_file = ENV.fetch("GITHUB_OUTPUT")
          File.open(output_file, "a") do |file|
            file.puts result
          end

        uses: ./.github/actions/reusable-e2e
        with:
          browser: ${{ matrix.browser }}
          deployment-target: liam-app
          environment: ${{ github.event.deployment.environment }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          should-run: ${{ steps.check.outputs.should_run }}
          ref: ${{ github.event.deployment.sha }}
          test-project: liam-app
          url: ${{ github.event.deployment_status.target_url }}

      - name: liam-erd-sample-e2e_tests
        id: check
        shell: ruby {0}
        working-directory: ${{ github.workspace }}
        run: |
          event_name      = "${{ github.event_name }}"
          event_state     = "${{ github.event.deployment_status.state }}"
          environment_val = "${{ github.event.deployment.environment }}"
          target_url      = "${{ github.event.deployment_status.target_url }}"

          result =
            if event_name == "deployment_status" && event_state == "success"
              # Production deployment
              if environment_val.include?("Preview") && target_url.include?("liam-erd-sample")
                "should_run=true"
              # Preview deployment
              elsif (!environment_val.include?("Production") && !target_url.include?("liam-app-git-main")) && (environment_val.include?("Preview") && !target_url.include?("liam-docs") && !target_url.include?("liam-storybook"))
                "should_run=true"
              else
                "should_run=false"
              end
            else
              "should_run=false"
            end

          output_file = ENV.fetch("GITHUB_OUTPUT")
          File.open(output_file, "a") do |file|
            file.puts result
          end
        uses: ./.github/actions/reusable-e2e
        with:
          browser: ${{ matrix.browser }}
          deployment-target: liam-erd-sample
          environment: ${{ github.event.deployment.environment }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.deployment.sha }}
          test-project: liam-erd-sample
          url: ${{ github.event.deployment_status.target_url }}
