name: E2E Tests

on:
  deployment_status:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        browser: [chromium, 'Mobile Safari']
      fail-fast: false

    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout repo for local action resolution
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml', '**/playwright.config.ts') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps
        shell: bash
        work-directory: frontend/internal-packages/e2e/test-results/

      - name: Install system dependencies for WebKit
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: pnpm exec playwright install-deps webkit
        shell: bash
        work-directory: frontend/internal-packages/e2e/test-results/

      - name: liam-app-e2e_tests
        if: github.event.deployment_status.state == 'success' &&
          contains(github.event.deployment.environment, 'Production') &&
          contains(github.event.deployment.environment, 'liam-app') &&
          contains(github.event.deployment_status.target_url, 'liam-app-git-main')
        uses: ./.github/actions/reusable-e2e
        with:
          browser: ${{ matrix.browser }}
          deployment-target: liam-app
          environment: ${{ github.event.deployment.environment }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.deployment.sha }}
          test-project: liam-app
          url: ${{ github.event.deployment_status.target_url }}

      - name: liam-erd-sample-e2e_tests
        if: github.event.deployment_status.state == 'success' &&
          contains(github.event.deployment_status.target_url, 'liam-erd-sample')
        uses: ./.github/actions/reusable-e2e
        with:
          browser: ${{ matrix.browser }}
          deployment-target: liam-erd-sample
          environment: ${{ github.event.deployment.environment }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.deployment.sha }}
          test-project: liam-erd-sample
          url: ${{ github.event.deployment_status.target_url }}
