name: E2E Tests

on:
  workflow_run:
    workflows: ['trigger_dev_production', 'trigger_dev_preview']
    types: [completed]
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        browser: [chromium, 'Mobile Safari']
      fail-fast: false

    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout repo for local action resolution
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml', '**/playwright.config.ts') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps
        shell: bash
        working-directory: frontend/internal-packages/e2e/

      - name: Install system dependencies for WebKit
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: pnpm exec playwright install-deps webkit
        shell: bash
        working-directory: frontend/internal-packages/e2e/

      - name: liam-app-e2e_tests
        if: github.event.workflow_run.conclusion == 'success' &&
          contains(github.event.workflow_run.name, 'trigger_dev_production')
        uses: ./.github/actions/reusable-e2e
        with:
          browser: ${{ matrix.browser }}
          deployment-target: liam-app
          environment: Production
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.workflow_run.head_sha }}
          test-project: liam-app
          url: https://liam-app-git-main.vercel.app

      - name: liam-erd-sample-e2e_tests
        if: github.event.workflow_run.conclusion == 'success' &&
          contains(github.event.workflow_run.name, 'trigger_dev_preview')
        uses: ./.github/actions/reusable-e2e
        with:
          browser: ${{ matrix.browser }}
          deployment-target: liam-erd-sample
          environment: Preview
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.workflow_run.head_sha }}
          test-project: liam-erd-sample
          url: https://liam-erd-sample-git-${{ github.event.workflow_run.head_branch }}.vercel.app
