name: E2E Tests

on:
  deployment_status:

concurrency:
  group: e2e-tests-${{ github.event.deployment.environment }}-${{ github.event.deployment.sha }}
  cancel-in-progress: false

jobs:
  check-deployment:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
      target_url: ${{ steps.snapshot.outputs.target_url }}
      sha: ${{ steps.snapshot.outputs.sha }}
    steps:
      - name: Snapshot deployment context to avoid race conditions
        id: snapshot
        run: |
          echo "env_val=${{ github.event.deployment.environment }}" >> $GITHUB_OUTPUT
          echo "target_url=${{ github.event.deployment_status.target_url }}" >> $GITHUB_OUTPUT
          echo "sha=${{ github.event.deployment.sha }}" >> $GITHUB_OUTPUT

      - name: Check deployment conditions
        id: check
        shell: ruby
        run: |
          event_name      = "${{ github.event_name }}"
          event_state     = "${{ github.event.deployment_status.state }}"
          environment_val = "${{ steps.snapshot.outputs.env_val }}"
          target_url      = "${{ steps.snapshot.outputs.target_url }}"

          result =
            if event_name == "deployment_status" && event_state == "success"
              if environment_val.include?("Preview") && target_url.include?("liam-app")
                "true"
              elsif environment_val.include?("Preview") && target_url.include?("liam-erd-sample")
                "true"
              elsif environment_val.include?("Production") && target_url.include?("liam-app-git-main")
                "true"
              else
                "false"
              end
            else
              "false"
            end

          echo "should_run=${result}" >> $GITHUB_OUTPUT
   e2e-tests:
    needs: check-deployment
    if: needs.check-deployment.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        browser: [chromium, 'Mobile Safari']
      fail-fast: false
    permissions:
      contents: read
      statuses: write
    defaults:
      run:
        working-directory: 'frontend/internal-packages/e2e'
    env:
      CI: true
      URL: ${{ needs.check-deployment.outputs.target_url }}
      ENVIRONMENT: ${{ github.event.deployment.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.check-deployment.outputs.sha }}
          persist-credentials: false

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml', '**/playwright.config.ts') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps

      - name: Install system dependencies for WebKit
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: pnpm exec playwright install-deps webkit

      - name: Run e2e tests
        run: pnpm exec playwright test --project="${{ matrix.browser }}"
        env:
          URL: ${{ needs.check-deployment.outputs.target_url }}

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.browser }}-${{ github.run_id }}-${{ github.job }}
          path: frontend/internal-packages/e2e/test-results/
          retention-days: 30

      - name: Post E2E status manually (with gh)
        if: always()
        run: |
          STATE="${{ job.status }}"
          CONTEXT="E2E Tests / e2e-tests (${{ matrix.browser }})"
          gh api repos/${{ github.repository }}/statuses/${{ needs.check-deployment.outputs.sha }} \
            --method POST \
            --field state="${STATE}" \
            --field context="${CONTEXT}" \
            --field description="E2E test result for ${{ matrix.browser }}: (${STATE})" \
            --field target_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
