name: frontend-ci

on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read
      pull-requests: read
    outputs:
      has-changes: ${{ steps.changes.outputs.has-changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            has-changes:
              - '.github/workflows/frontend-ci.yml'
              - '.github/actions/pnpm-setup/**'
              - './frontend/**'
              - '.syncpackrc'
              - 'biome.jsonc'
              - 'package.json'
              - 'pnpm-lock.yaml'
              - 'pnpm-workspace.yaml'
              - 'turbo.json'

  frontend-lint:
    needs: [setup-job]
    if: ${{ needs.setup-job.outputs.has-changes == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-setup
      - run: pnpm lint

  frontend-ci:
    needs: [setup-job]
    if: ${{ needs.setup-job.outputs.has-changes == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-setup
      - run: pnpm test:turbo

  check-supabase-types-diff:
    needs: [setup-job]
    if: ${{ needs.setup-job.outputs.has-changes == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./frontend/packages/db

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-setup
      - run: pnpm supabase:start
      - run: pnpm supabase:gen
      - name: Check for diff in generated types
        run: |
          git add supabase/database.types.ts
          if ! git diff HEAD --ignore-space-at-eol --exit-code supabase/database.types.ts; then
            echo "Generated types differ from committed file."
            git diff HEAD supabase/database.types.ts
            exit 1
          else
            echo "Generated types are up-to-date."
            exit 0
          fi
