name: ghalint

on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read
      pull-requests: read
    outputs:
      has-changes: ${{ steps.changes.outputs.has-changes }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            has-changes:
              - '.github/workflows/ghalint.yml'
              - '.github/workflows/**/*.yml'
              - '.github/workflows/**/*.yaml'

  ghalint:
    needs: [setup-job]
    if: ${{ needs.setup-job.outputs.has-changes == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      
      - name: Download and verify ghalint
        run: |
          GHALINT_VERSION="1.5.1"
          curl -L -o ghalint.tar.gz "https://github.com/suzuki-shunsuke/ghalint/releases/download/v${GHALINT_VERSION}/ghalint_${GHALINT_VERSION}_linux_amd64.tar.gz"
          
          # Verify checksum
          hash=$(sha256sum ghalint.tar.gz | awk '{ print $1 }')
          expected_hash="e791009d9361c8f0f0d2e2b9b67d428fe2dddc6694cbfec9954e2502a8e0e0ff"
          
          if [ "$hash" = "$expected_hash" ]; then
            tar -xzf ghalint.tar.gz
            chmod +x ghalint
            sudo mv ghalint /usr/local/bin/
          else
            echo "Checksum verification failed!"
            echo "Expected: $expected_hash"
            echo "Got: $hash"
            exit 1
          fi
          
      - name: Run ghalint
        run: ghalint run
