name: ghalint

on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read
      pull-requests: read
    outputs:
      has-changes: ${{ steps.changes.outputs.has-changes }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            has-changes:
              - '.github/workflows/ghalint.yml'
              - '.github/workflows/**/*.yml'
              - '.github/workflows/**/*.yaml'

  ghalint:
    needs: [setup-job]
    if: ${{ needs.setup-job.outputs.has-changes == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      
      - name: Download ghalint
        run: |
          curl -L -o ghalint.tar.gz https://github.com/suzuki-shunsuke/ghalint/releases/download/v1.5.1/ghalint_1.5.1_linux_amd64.tar.gz
          tar -xzf ghalint.tar.gz
          chmod +x ghalint
          sudo mv ghalint /usr/local/bin/
          
      - name: Run ghalint
        run: |
          # Run ghalint but don't fail CI initially - just report issues
          ghalint run || echo "ghalint found security issues - see output above for details"
