name: E2E Tests for liam-erd-sample

on:
  deployment_status:

concurrency:
  group: e2e-tests-liam-app-${{ github.event.deployment.sha }}
  cancel-in-progress: false

jobs:
  e2e-tests:
    if: >
      github.event.deployment_status.state == 'success' &&
      contains(github.event.deployment_status.target_url, 'liam-erd-sample')
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        browser: [chromium, 'Mobile Safari']
      fail-fast: false

    permissions:
      contents: read
      statuses: write

    defaults:
      run:
        working-directory: frontend/internal-packages/e2e

    env:
      CI: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.deployment.sha }}
          persist-credentials: false

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml', '**/playwright.config.ts') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install browsers
        run: pnpm exec playwright install --with-deps

      - name: Run E2E tests
        run: pnpm exec playwright test --project="${{ matrix.browser }}"
        env:
          URL: ${{ github.event.deployment_status.target_url }}
          ENVIRONMENT: ${{ github.event.deployment.environment }}

      - name: Upload test results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.browser }}
          path: frontend/internal-packages/e2e/test-results/

      - name: Post test status
        if: always()
        run: |
          gh api repos/${{ github.repository }}/statuses/${{ github.sha }} \
            --method POST \
            --field state="${{ job.status }}" \
            --field context="E2E Tests / liam-erd-sample / ${{ matrix.browser }}"
            --field description="liam-erd-sample E2E test result: ${{ job.status }}"
            --field target_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
