name: Daily Lint Check

on:
  schedule:
    - cron: '0 0 * * *' # JST09:00 (UTC00:00)
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Linter with Full Output
        run: pnpm turbo lint --output-logs=full > lint-result.txt 2>&1

      - name: Check for Warnings
        id: lint_check
        run: |
          grep -i 'warning\|warn' lint-result.txt > warnings.txt || true
          echo "has_warning=$(test -s warnings.txt && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: Post to Issue (if warning exists)
        if: steps.lint_check.outputs.has_warning == 'true'
        run: |
          WARNING_COUNT=$(grep -i 'warning\|warn' warnings.txt | wc -l)
          
          # Read template and replace WARNING_COUNT placeholder
          ISSUE_BODY=$(sed "s/WARNING_COUNT/$WARNING_COUNT/g" .github/workflows/templates/lint-and-notify.md)
          
          gh issue create \
            --title "Daily Lint Warning Report - $(date '+%Y-%m-%d')" \
            --body "$ISSUE_BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
