name: PR Agent for Devin PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-agent-review:
    if: github.actor == 'devin-ai-integration[bot]' || contains(github.event.pull_request.body, 'Link to Devin run') || contains(github.event.pull_request.body, 'https://app.devin.ai/sessions/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: PR Agent Review
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: /review
          
      - name: PR Agent Describe
        uses: qodo-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: /describe
