# NOTE: This workflow is configured as a Trusted Publisher on npmjs.com
# The workflow filename "release.yml" is registered in the Trusted Publisher settings.
# If you rename this file, you must also update the Trusted Publisher configuration on npmjs.com
# ex. https://www.npmjs.com/package/@liam-hq/cli/access

name: release
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  actions: write # for `Trigger released_package_test.yml via API`
  id-token: write
  contents: write
  packages: write
  pull-requests: write
  issues: read

jobs:
  create_release_pull_request_or_publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        id: app-token
        with:
          app-id: ${{ vars.CHANGESET_CI_TRIGGER_APP_ID }}
          private-key: ${{ secrets.CHANGESET_CI_TRIGGER_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
      - uses: ./.github/actions/pnpm-setup

      # NOTE: Temporary workaround
      # - "Trusted publishing" requires npm 11.5.1+.
      #   See: https://docs.npmjs.com/trusted-publishers
      - name: Update npm
        run: npm update -g npm

      - name: Create Release Pull Request or Publish to npm
        id: changesets-action
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Trigger released_package_test.yml via API
        if: ${{ steps.changesets-action.outputs.published == 'true' }}
        run: |
          version=$(cat frontend/packages/cli/package.json | jq -r '.version')
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/actions/workflows/released_package_test.yml/dispatches \
               -d '{"ref":"main", "inputs": { "delay_seconds": "60", "version": "'${version}'" }}'

      - name: Slack Notification on Failure
        if: failure()
        uses: tokorom/action-slack-incoming-webhook@d57bf1eb618f3dae9509afefa70d5774ad3d42bf # v1.3.0
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_CLI_CI_WEBHOOK_URL }}
        with:
          text: "main branch failure(.github/workflows/release.yml)"
          attachments: |
            [
              {
                "color": "bad",
                "fields": [
                  {
                    "title": "Result",
                    "value": "failure"
                  },
                  {
                    "title": "Job URL",
                    "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
