# Test Suggestion Agent
# Analyzes PR changes and suggests appropriate test coverage
name: Test Suggestion Agent

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  suggest-tests:
    # Run on PR events or when someone comments /suggest-tests
    if: |
      github.event_name == 'pull_request' || 
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request && 
       contains(github.event.comment.body, '/suggest-tests'))
    
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0  # Need full history for accurate diff analysis
          persist-credentials: false

      - name: Setup pnpm
        uses: ./.github/actions/pnpm-setup

      - name: Analyze PR and Suggest Tests
        uses: anthropics/claude-code-action@8c08381496931f68f7918d3788c75ec258f2698b # beta
        with:
          direct_prompt: |
            /suggest-tests This will analyze the PR changes and provide comprehensive test coverage suggestions.
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          allowed_tools: "mcp__github__get_pull_request,mcp__github__get_pull_request_diff,mcp__github__add_issue_comment,mcp__github__create_pending_pull_request_review,mcp__github__add_pull_request_review_comment_to_pending_review,mcp__github__submit_pending_pull_request_review"