name: trigger_dev_preview
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - .github/workflows/trigger_dev_preview.yml
      - frontend/internal-packages/jobs/**
      - frontend/packages/db-structure/**
      - frontend/packages/github/**
      - frontend/internal-packages/db/**
      - turbo.json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger_dev:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/pnpm-setup

      - name: Deploy to trigger.dev preview
        if: github.event.action != 'closed'
        shell: bash
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
          TRIGGER_PROJECT_ID: ${{ vars.TRIGGER_PROJECT_ID }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          NEXT_PUBLIC_ENV_NAME: preview
          VERCEL_GIT_COMMIT_REF: ${{ github.head_ref }}
        run: pnpm deploy:jobs -- --env preview --branch ${{ github.head_ref }}

      - name: Archive trigger.dev preview
        if: github.event.action == 'closed'
        shell: bash
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
          TRIGGER_PROJECT_ID: ${{ vars.TRIGGER_PROJECT_ID }}
        run: |
          pnpm --filter @liam-hq/jobs exec trigger preview archive --branch ${{ github.head_ref }}
